### ISSUE TITLE
Code Inquiry: Load predictions

### ISSUE THREAD

**Issue by arifulhoque7** [gabrielbianchin/TEMPROT#4]
`preds_blast = np.load('predictions/bp-blast.npy')
preds_temprot = np.load('predictions/bp-temprot.npy')`

From where can we get this files. (bp-blast.npy , bp-temport.npy).
Also want to know the process to run the code step by step in colab. Can you please help?
Thank you.

**Comment by gabrielbianchin** [comment]
Hi @arifulhoque7, thanks for your comment. 

These numpy arrays are generated by meta-classifier.py and blast.py files. If you prefer, I can make it available (the predictions when I ran the code).

You can run in colab following [this](https://github.com/gabrielbianchin/TEMPROT#reproducibility) step by step section. You should create data and predictions folders inside TEMPROT git folder first and run `! sudo apt install ncbi-blast+` and `! pip install ktrain` to install BLAST and ktrain. To run the files, you can use `! python [file.py]`

I guess that you should modify `fine-tuning.py` file because it takes many hours to run (something between 30 and 40 hours).

**Comment by arifulhoque7** [comment]
Hello @gabrielbianchin, Thank you so much for the reply.
It will be very helpful for me if you make the predictions available. 
Also, I want to implement this code in colab. As, we know colab supports 24 hours runtime. I need recomendations and directions how can I modify `fine-tuning.py` file.

**Comment by gabrielbianchin** [comment]
Hi @arifulhoque7.

You can find the predictions [here](https://drive.google.com/drive/folders/16WnhH672_opl3FyFILDnRRHS1wzcPyHh?usp=drive_link). 

You can add the following line after `model = t.get_classifier()` in `fine-tuning.py` file. This line will load the weights of the folder that you saved the model weights and restart the training step:
`model.load_weights(#path to the weights)`
